apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-front
  template:
    metadata:
      labels:
        app: book-front
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: book-front
        image: {{ACR_LOGINSERVER}}/book-front:v{{BUILD_NUMBER}}
        ports:
        - containerPort: 8080
          name: book-front
        env: 
        - name: VITE_AXIOS_BASE_URL
          value: "http://4.191.74.246/"
        resources:
          requests:
            cpu: 1m
            memory: 200Mi
          limits:
            cpu: 1000m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: book-front
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: book-front
  type: LoadBalancer
